making the workflow

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -97,72 +97,72 @@ jobs:
         terraform -chdir=./staging fmt -check 
 
     # validating the terraform code for any syntax error
-    - name: Terraform validate
-      id: validate
-      run: |
-          terraform -chdir=./production validate 
-          terraform -chdir=./staging validate
+    # - name: Terraform validate
+    #   id: validate
+    #   run: |
+    #       terraform -chdir=./production validate 
+    #       terraform -chdir=./staging validate
 
 
-    # Generates an execution plan for Terraform
-    - name: Terraform Plan
-      if: github.event_name == 'pull_request'
-      id: plan
-      run: terraform -chdir=./production plan -no-color 
+    # # Generates an execution plan for Terraform
+    # - name: Terraform Plan
+    #   if: github.event_name == 'pull_request'
+    #   id: plan
+    #   run: terraform -chdir=./production plan -no-color 
 
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+    # - name: Terraform Plan Status
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
 
 
 
       
-    # Add a comment to pull requests with results
-    - name: add-results-comment
-      id: comment
-      uses: actions/github-script@v6
-      if: github.event_name == 'pull_request'
-      env:
-        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+    # # Add a comment to pull requests with results
+    # - name: add-results-comment
+    #   id: comment
+    #   uses: actions/github-script@v6
+    #   if: github.event_name == 'pull_request'
+    #   env:
+    #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
       
 
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-          #### Terraform Format  🖌\`${{ steps.format.outcome }}\`
-          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+    #   with:
+    #     github-token: ${{ secrets.GITHUB_TOKEN }}
+    #     script: |
+    #       const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+    #       #### Terraform Format  🖌\`${{ steps.format.outcome }}\`
+    #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+    #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
       
-          <details><summary>Show Plan Changes</summary>
+    #       <details><summary>Show Plan Changes</summary>
           
-          \`\`\`\n
-          ${process.env.PLAN}
-          \`\`\`
+    #       \`\`\`\n
+    #       ${process.env.PLAN}
+    #       \`\`\`
           
-          </details>
+    #       </details>
 
       
           
-          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
+    #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
             
-          github.rest.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
+    #       github.rest.issues.createComment({
+    #         issue_number: context.issue.number,
+    #         owner: context.repo.owner,
+    #         repo: context.repo.repo,
+    #         body: output
+    #       })
 
-      # On push to main, build or change infrastructure according to Terraform configuration files
-      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
-    - name: Terraform Apply
-      # env:
-      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #   AWS_REGION: ${{ secrets.AWS_REGION }}
-      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+    #   # On push to main, build or change infrastructure according to Terraform configuration files
+    #   # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
+    # - name: Terraform Apply
+    #   # env:
+    #   #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+    #   #   AWS_REGION: ${{ secrets.AWS_REGION }}
+    #   #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
 
-      run: terraform -chdir=./production  apply -auto-approve
+    #   run: terraform -chdir=./production  apply -auto-approve
 
 
   terratest:
@@ -317,7 +317,7 @@ jobs:
   deploy-staging:
     name: 'deploy-staging'
     environment: staging
-    if: needs.terratest.result == 'success' && needs.lint-test-build == 'success''
+    if: needs.terratest.result == 'success' && needs.lint-test-build == 'success'
     runs-on: ubuntu-latest
  
     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
